FROM ubuntu:18.10

## CLM5.0
MAINTAINER "Dongdong Kong"

WORKDIR /model
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt install -y --no-install-recommends \
    ca-certificates \
    libxml2-utils libxml-libxml-perl \
    python \
 && apt-get clean
# libopenmpi-dev 

RUN git clone -b release-clm5.0 https://github.com/ESCOMP/ctsm \
 && cd ctsm && ./manage_externals/checkout_externals && cd ..
